data:
  - attributes:
      created_at: '2020-04-30T01:00:24'
      destination_override_endpoint: 'NGROK_URL_HERE'
      entries:
        - classifiers: {}
          config:
            condition: OR
            expression: null
            rules:
              - condition: null
                expression:
                  field: PathInfo
                  operator: matches
                  type: string
                  values:
                    - /users
                rules: null
          id: f5baa170-b2be-4776-b25b-a17e61c1ab7d
          id_selector: null
          operation: REDACT
          operations: null
          phase: REQUEST
          public_token_generator: UUID
          targets:
            - body
          token_manager: PERSISTENT
          transformer: JSON_PATH
          transformer_config:
            - $.ssn
          transformer_config_map: null
        - classifiers: {}
          config:
            condition: AND
            rules:
              - condition: null
                expression:
                  field: PathInfo
                  operator: matches
                  type: string
                  values:
                    - /users
          id: d1a8e373-b606-4ac6-833b-0b6b0892757a
          id_selector: null
          operation: ENRICH
          operations: null
          phase: RESPONSE
          public_token_generator: UUID
          targets:
            - body
          token_manager: PERSISTENT
          transformer: JSON_PATH
          transformer_config:
            - $.userInfo.ssn
          transformer_config_map: null
          type: null
      host_endpoint: (.*)\.verygoodproxy\.com
      id: c2b85e2e-0b15-4dc6-a18c-3b15860819da
      ordinal: null
      port: 80
      protocol: http
      source_endpoint: '*'
      tags:
        name: echo.apps.verygood.systems-green-tv
        source: RouteContainer
      updated_at: '2020-05-27T18:11:24'
    id: c2b85e2e-0b15-4dc6-a18c-3b15860819da
    type: rule_chain
version: 1
