version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - run: cd ~/project/server
      - run:
          command: |
            sudo pip install -r requirements.txt
            pytest
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: trl